# Generated by Django 5.1.1 on 2024-09-13 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priceplan',
            old_name='desc',
            new_name='info',
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.service'),
        ),
    ]
