# Generated by Django 5.1.1 on 2024-09-14 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_post_likes_alter_likepost_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AddField(
            model_name='commentpost',
            name='post',
            field=models.ForeignKey(default=1287, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.post'),
            preserve_default=False,
        ),
    ]
