# Generated by Django 5.1.1 on 2024-09-15 08:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_post_comments_commentpost_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='portfolio',
            field=models.ForeignKey(default=2295, on_delete=django.db.models.deletion.CASCADE, to='home.portfolio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='rating',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
