# Generated by Django 5.1.1 on 2024-09-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contactuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypost',
            name='title',
            field=models.CharField(max_length=125, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='desc',
            field=models.CharField(max_length=125, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=125, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.CharField(max_length=125, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=125, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='service',
            name='desc',
            field=models.CharField(max_length=125, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=125, verbose_name='Title'),
        ),
    ]
